# Generated by Selenium IDE
require 'selenium-webdriver'
# require 'json' không cần thiết
describe 'SelectVisa' do
 
# '@' bị lỗi khi chạy nên em chuyển sang '$' nếu không được thì đổi lại giúp e nha ^^
  
  before(:each) do
    $driver = Selenium::WebDriver.for :chrome 
#   $vars = {} # biến var không cần thiết
  end
  
  # nên mở trang web trong 1 cái before :each để sau này có thêm vài cái "it" nữa cũng k cần phải code lại 
  before(:each) do
    $driver.get('http://www.practiceselenium.com/check-out.html')
  end  
  
  # nên để after :all thay vì :each để khi tất cả các "it" chạy xong mới đóng browser lại (trường hợp có nhiều "it")
  after(:all) do
    $driver.quit
  end
  
  it 'selectVisa' do
#   $driver.get('http://www.practiceselenium.com/check-out.html')
    $driver.manage.window.resize_to(1526, 848)
    $driver.find_element(:id, 'card_type').click
    dropdown = $driver.find_element(:id, 'card_type')
    dropdown.find_element(:xpath, "//option[. = 'Visa']").click
    $driver.find_element(:id, 'card_type').click
  end
end
