# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'SelectVisa' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'selectVisa' do
    @driver.get('http://www.practiceselenium.com/check-out.html')
    @driver.manage.window.resize_to(1526, 848)
    @driver.find_element(:id, 'card_type').click
    dropdown = @driver.find_element(:id, 'card_type')
    dropdown.find_element(:xpath, "//option[. = 'Visa']").click
    @driver.find_element(:id, 'card_type').click
  end
end
